import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';

function App() {
  return (
    <div className="min-h-screen bg-background p-8">
      <div className="max-w-4xl mx-auto space-y-8">
        <header className="text-center space-y-4">
          <h1 className="text-4xl font-bold tracking-tight">
            todo-ikea
          </h1>
          <p className="text-xl text-muted-foreground">
            simple todo app
          </p>
          <Badge variant="secondary">Generated by Ingvar Spark</Badge>
        </header>

        <Card>
          <CardHeader>
            <CardTitle>🚀 Your App is Ready!</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p>This is your generated Spark app. Start building amazing things!</p>
            <Button>Get Started</Button>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

export default App;