name: Auto Assign to Project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add to project
        uses: actions/add-to-project@v1.0.2
        with:
          # Configure this with: leo project setup
          # Or manually set PROJECT_URL secret with your project URL
          project-url: ${{ secrets.PROJECT_URL }}
